package app.utk.main.exception;

/**
 * @author UtkarshRathore on 02-12-2021
 **/
public class ExistingContactException {
}
